package com.example.cozinhai;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class IngredientData {
    public static List<SeasonalIngredient> getIngredients() {
        List<SeasonalIngredient> list = new ArrayList<>();
        list.add(new SeasonalIngredient("abacaxi", "Abacaxi", "noto:pineapple", "fruta", Arrays.asList(1, 3, 9, 10, 11, 12), "abacaxi"));
        list.add(new SeasonalIngredient("abacate", "Abacate", "noto:avocado", "fruta", Arrays.asList(2, 3, 4, 5), "abacate"));
        list.add(new SeasonalIngredient("acerola", "Acerola", "noto:cherries", "fruta", Arrays.asList(9, 10, 11, 12), "acerola"));
        list.add(new SeasonalIngredient("ameixa", "Ameixa", "noto:plum", "fruta", Arrays.asList(2, 3, 4, 12), "ameixa"));
        list.add(new SeasonalIngredient("amora", "Amora", "material-symbols:nutrition", "fruta", Arrays.asList(10, 11), "amora"));
        list.add(new SeasonalIngredient("banana", "Banana", "noto:banana", "fruta", Arrays.asList(3, 4, 5, 6, 7, 8, 9, 10, 11, 12), "banana"));
        list.add(new SeasonalIngredient("caju", "Caju", "material-symbols:nutrition", "fruta", Arrays.asList(6, 8, 9), "caju"));
        list.add(new SeasonalIngredient("caqui", "Caqui", "noto:tangerine", "fruta", Arrays.asList(4, 5), "caqui"));
        list.add(new SeasonalIngredient("carambola", "Carambola", "material-symbols:star", "fruta", Arrays.asList(1, 2, 6, 7, 8), "carambola"));
        list.add(new SeasonalIngredient("cidra", "Cidra", "noto:lemon", "fruta", Arrays.asList(4), "cidra"));
        list.add(new SeasonalIngredient("coco", "Coco", "noto:coconut", "fruta", Arrays.asList(1, 2, 3, 9, 10, 11, 12), "coco"));
        list.add(new SeasonalIngredient("cupuacu", "Cupuaçu", "material-symbols:nutrition", "fruta", Arrays.asList(11, 12), "cupuacu"));
        list.add(new SeasonalIngredient("figo", "Figo", "material-symbols:nutrition", "fruta", Arrays.asList(1, 2, 3, 12), "figo"));
        list.add(new SeasonalIngredient("fruta-do-conde", "Fruta do Conde", "material-symbols:nutrition", "fruta", Arrays.asList(1, 2, 3), "fruta-do-conde"));
        list.add(new SeasonalIngredient("goiaba", "Goiaba", "material-symbols:nutrition", "fruta", Arrays.asList(2, 3), "goiaba"));
        list.add(new SeasonalIngredient("jaca", "Jaca", "material-symbols:nutrition", "fruta", Arrays.asList(2, 3, 4, 5, 11, 12), "jaca"));
        list.add(new SeasonalIngredient("jabuticaba", "Jabuticaba", "noto:grapes", "fruta", Arrays.asList(9, 10, 11), "jabuticaba"));
        list.add(new SeasonalIngredient("kiwi", "Kiwi", "noto:kiwi-fruit", "fruta", Arrays.asList(4, 5, 6, 7, 8), "kiwi"));
        list.add(new SeasonalIngredient("laranja", "Laranja", "noto:tangerine", "fruta", Arrays.asList(1, 6, 8, 9, 10, 11, 12), "laranja"));
        list.add(new SeasonalIngredient("lima", "Lima", "noto:lemon", "fruta", Arrays.asList(6, 8, 9), "lima"));
        list.add(new SeasonalIngredient("limao", "Limão", "noto:lemon", "fruta", Arrays.asList(3), "limao"));
        list.add(new SeasonalIngredient("lichia", "Lichia", "material-symbols:nutrition", "fruta", Arrays.asList(12), "lichia"));
        list.add(new SeasonalIngredient("maca", "Maçã", "noto:red-apple", "fruta", Arrays.asList(2, 3, 4, 5, 6, 7, 8, 9), "maca"));
        list.add(new SeasonalIngredient("mamao", "Mamão", "material-symbols:nutrition", "fruta", Arrays.asList(1, 3, 6, 8, 9, 10, 11, 12), "mamao"));
        list.add(new SeasonalIngredient("manga", "Manga", "noto:mango", "fruta", Arrays.asList(9, 10, 11, 12), "manga"));
        list.add(new SeasonalIngredient("maracuja", "Maracujá", "material-symbols:nutrition", "fruta", Arrays.asList(1, 11, 12), "maracuja"));
        list.add(new SeasonalIngredient("melancia", "Melancia", "noto:watermelon", "fruta", Arrays.asList(1, 10, 11, 12), "melancia"));
        list.add(new SeasonalIngredient("melao", "Melão", "noto:melon", "fruta", Arrays.asList(10, 11, 12), "melao"));
        list.add(new SeasonalIngredient("mexerica", "Mexerica", "noto:tangerine", "fruta", Arrays.asList(6, 7, 8), "mexerica"));
        list.add(new SeasonalIngredient("morango", "Morango", "noto:strawberry", "fruta", Arrays.asList(6, 8), "morango"));
        list.add(new SeasonalIngredient("nectarina", "Nectarina", "noto:peach", "fruta", Arrays.asList(1, 3), "nectarina"));
        list.add(new SeasonalIngredient("nespera", "Nêspera", "material-symbols:nutrition", "fruta", Arrays.asList(9), "nespera"));
        list.add(new SeasonalIngredient("pera", "Pera", "noto:pear", "fruta", Arrays.asList(2, 3, 4, 5), "pera"));
        list.add(new SeasonalIngredient("pessego", "Pêssego", "noto:peach", "fruta", Arrays.asList(2, 3, 10, 11, 12), "pessego"));
        list.add(new SeasonalIngredient("pitanga", "Pitanga", "noto:cherries", "fruta", Arrays.asList(10, 11, 12), "pitanga"));
        list.add(new SeasonalIngredient("seriguela", "Seriguela", "noto:plum", "fruta", Arrays.asList(2, 3), "seriguela"));
        list.add(new SeasonalIngredient("tangerina", "Tangerina", "noto:tangerine", "fruta", Arrays.asList(3, 4, 5, 6, 7, 8, 9), "tangerina"));
        list.add(new SeasonalIngredient("uva", "Uva", "noto:grapes", "fruta", Arrays.asList(1, 2, 3, 4, 5, 7), "uva"));

        list.add(new SeasonalIngredient("acelga", "Acelga", "material-symbols:eco", "verdura", Arrays.asList(3, 11, 12), "acelga"));
        list.add(new SeasonalIngredient("agrao", "Agrião", "material-symbols:eco", "verdura", Arrays.asList(6, 7, 8), "agrao"));
        list.add(new SeasonalIngredient("alface", "Alface", "material-symbols:eco", "verdura", Arrays.asList(1, 3, 4, 11, 12), "alface"));
        list.add(new SeasonalIngredient("alho-poro", "Alho-poró", "material-symbols:eco", "verdura", Arrays.asList(3, 4, 5, 6, 7, 8, 9, 10), "alho-poro"));
        list.add(new SeasonalIngredient("almeirao", "Almeirão", "material-symbols:eco", "verdura", Arrays.asList(4, 5, 9, 10, 11, 12), "almeirao"));
        list.add(new SeasonalIngredient("brocolis", "Brócolis", "noto:broccoli", "verdura", Arrays.asList(6, 8, 9, 10), "brocolis"));
        list.add(new SeasonalIngredient("catalonha", "Catalonha", "material-symbols:eco", "verdura", Arrays.asList(4, 9, 10), "catalonha"));
        list.add(new SeasonalIngredient("cebolinha", "Cebolinha", "material-symbols:eco", "verdura", Arrays.asList(1, 9, 11, 12), "cebolinha"));
        list.add(new SeasonalIngredient("chicoria", "Chicória", "material-symbols:eco", "verdura", Arrays.asList(6, 7, 8, 9, 10), "chicoria"));
        list.add(new SeasonalIngredient("coentro", "Coentro", "material-symbols:eco", "verdura", Arrays.asList(3, 6, 7, 8, 9, 10, 11, 12), "coentro"));
        list.add(new SeasonalIngredient("couve", "Couve", "material-symbols:eco", "verdura", Arrays.asList(1, 6, 7, 9, 10, 11, 12), "couve"));
        list.add(new SeasonalIngredient("couve-flor", "Couve-flor", "material-symbols:eco", "verdura", Arrays.asList(6, 8, 9, 10), "couve-flor"));
        list.add(new SeasonalIngredient("endivia", "Endívia", "material-symbols:eco", "verdura", Arrays.asList(3), "endivia"));
        list.add(new SeasonalIngredient("erva-doce", "Erva-doce", "material-symbols:eco", "verdura", Arrays.asList(5, 6, 7, 8, 9), "erva-doce"));
        list.add(new SeasonalIngredient("escarola", "Escarola", "material-symbols:eco", "verdura", Arrays.asList(2, 3, 4, 6, 8), "escarola"));
        list.add(new SeasonalIngredient("espinafre", "Espinafre", "material-symbols:eco", "verdura", Arrays.asList(6, 7, 8, 9, 10, 11, 12), "espinafre"));
        list.add(new SeasonalIngredient("folha-de-uva", "Folha de Uva", "material-symbols:eco", "verdura", Arrays.asList(9), "folha-de-uva"));
        list.add(new SeasonalIngredient("hortela", "Hortelã", "material-symbols:eco", "verdura", Arrays.asList(2, 9, 10), "hortela"));
        list.add(new SeasonalIngredient("louro", "Louro", "material-symbols:eco", "verdura", Arrays.asList(5), "louro"));
        list.add(new SeasonalIngredient("mostarda", "Mostarda", "material-symbols:eco", "verdura", Arrays.asList(6, 7, 8, 9, 10), "mostarda"));
        list.add(new SeasonalIngredient("oregano", "Orégano", "material-symbols:eco", "verdura", Arrays.asList(9), "oregano"));
        list.add(new SeasonalIngredient("repolho", "Repolho", "material-symbols:eco", "verdura", Arrays.asList(2, 3, 4), "repolho"));
        list.add(new SeasonalIngredient("rucula", "Rúcula", "material-symbols:eco", "verdura", Arrays.asList(3, 6, 8, 10, 11, 12), "rucula"));
        list.add(new SeasonalIngredient("salsao", "Salsão", "material-symbols:eco", "verdura", Arrays.asList(7), "salsao"));
        list.add(new SeasonalIngredient("salsa", "Salsa", "material-symbols:eco", "verdura", Arrays.asList(1, 3, 11, 12), "salsa"));

        list.add(new SeasonalIngredient("abobora", "Abóbora", "noto:pumpkin", "legume", Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), "abobora"));
        list.add(new SeasonalIngredient("abobrinha", "Abobrinha", "material-symbols:nutrition", "legume", Arrays.asList(1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12), "abobrinha"));
        list.add(new SeasonalIngredient("alcachofra", "Alcachofra", "material-symbols:nutrition", "legume", Arrays.asList(9), "alcachofra"));
        list.add(new SeasonalIngredient("aspargos", "Aspargos", "material-symbols:nutrition", "legume", Arrays.asList(9), "aspargos"));
        list.add(new SeasonalIngredient("batata-doce", "Batata-doce", "material-symbols:nutrition", "legume", Arrays.asList(5, 7, 9), "batata-doce"));
        list.add(new SeasonalIngredient("berinjela", "Berinjela", "noto:eggplant", "legume", Arrays.asList(2, 3, 4, 5, 9, 10, 11, 12), "berinjela"));
        list.add(new SeasonalIngredient("beterraba", "Beterraba", "material-symbols:nutrition", "legume", Arrays.asList(1, 2, 3, 4, 5, 9, 10, 11, 12), "beterraba"));
        list.add(new SeasonalIngredient("cara", "Cará", "material-symbols:nutrition", "legume", Arrays.asList(2, 3, 4, 5, 6, 8), "cara"));
        list.add(new SeasonalIngredient("cenoura", "Cenoura", "noto:carrot", "legume", Arrays.asList(5, 6, 7, 8, 9, 10, 11, 12), "cenoura"));
        list.add(new SeasonalIngredient("chuchu", "Chuchu", "material-symbols:nutrition", "legume", Arrays.asList(2, 3, 4, 5, 10, 11, 12), "chuchu"));
        list.add(new SeasonalIngredient("cogumelo", "Cogumelo", "noto:mushroom", "legume", Arrays.asList(9), "cogumelo"));
        list.add(new SeasonalIngredient("ervilha", "Ervilha", "material-symbols:nutrition", "legume", Arrays.asList(6, 8, 9), "ervilha"));
        list.add(new SeasonalIngredient("fava", "Fava", "material-symbols:nutrition", "legume", Arrays.asList(6, 8, 9), "fava"));
        list.add(new SeasonalIngredient("gengibre", "Gengibre", "material-symbols:nutrition", "legume", Arrays.asList(2, 3, 4, 5), "gengibre"));
        list.add(new SeasonalIngredient("inhame", "Inhame", "material-symbols:nutrition", "legume", Arrays.asList(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), "inhame"));
        list.add(new SeasonalIngredient("jilo", "Jiló", "material-symbols:nutrition", "legume", Arrays.asList(3), "jilo"));
        list.add(new SeasonalIngredient("mandioca", "Mandioca", "material-symbols:nutrition", "legume", Arrays.asList(5, 6, 7, 10, 11, 12), "mandioca"));
        list.add(new SeasonalIngredient("mandioquinha", "Mandioquinha", "material-symbols:nutrition", "legume", Arrays.asList(5, 6, 7, 8, 10, 11, 12), "mandioquinha"));
        list.add(new SeasonalIngredient("milho-verde", "Milho-verde", "noto:ear-of-corn", "legume", Arrays.asList(2, 3, 7), "milho-verde"));
        list.add(new SeasonalIngredient("nabo", "Nabo", "material-symbols:nutrition", "legume", Arrays.asList(3, 4, 5, 6, 7, 8), "nabo"));
        list.add(new SeasonalIngredient("palmito", "Palmito", "material-symbols:nutrition", "legume", Arrays.asList(7), "palmito"));
        list.add(new SeasonalIngredient("pepino", "Pepino", "noto:cucumber", "legume", Arrays.asList(1, 2, 3, 4, 7, 9, 10, 11, 12), "pepino"));
        list.add(new SeasonalIngredient("pimentao", "Pimentão", "noto:bell-pepper", "legume", Arrays.asList(1, 2, 6, 8, 9, 10, 11, 12), "pimentao"));
        list.add(new SeasonalIngredient("quiabo", "Quiabo", "material-symbols:nutrition", "legume", Arrays.asList(1, 2, 3, 10, 11, 12), "quiabo"));
        list.add(new SeasonalIngredient("rabanete", "Rabanete", "material-symbols:nutrition", "legume", Arrays.asList(5, 6, 7, 8, 9, 10, 11, 12), "rabanete"));
        list.add(new SeasonalIngredient("tomate", "Tomate", "noto:tomato", "legume", Arrays.asList(1, 2, 3, 4, 9, 10, 11, 12), "tomate"));
        list.add(new SeasonalIngredient("tomate-caqui", "Tomate-caqui", "noto:tomato", "legume", Arrays.asList(9), "tomate-caqui"));
        return list;
    }
}
